ignored = ["github.com/elyby/chrly"]

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "^1.6.1"

[[constraint]]
  name = "github.com/mediocregopher/radix.v2"
  branch = "master"

[[constraint]]
  name = "github.com/mono83/slf"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  branch = "master"

[[constraint]]
  name = "github.com/SermoDigital/jose"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/thedevsaddam/govalidator"
  version = "^1.9.6"

[[constraint]]
  name = "github.com/asaskevich/EventBus"
  source = "https://github.com/erickskrauch/EventBus.git"
  branch = "publish_nil_values"

[[constraint]]
  name = "github.com/etherlabsio/healthcheck"
  version = "2.0.3"

[[constraint]]
  name = "github.com/goava/di"
  branch = "master"

# Testing dependencies

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/h2non/gock"
  version = "^1.0.6"
